### ISSUE TITLE
Env [KNOWLEDGE_HOME] was not found.

### ISSUE THREAD

**Issue by naotoshin** [support-project/knowledge#1013]
AWS EC2上で稼働するtomcat8上に1.12.0のwarファイルを配置したところ、表題のエラーが発生し、アプリケーションが起動しませんでした。
同様の事象が発生するかご確認いただき、適宜対応いただきたいです。

※warファイルは以下よりダウンロードしています。
https://github.com/support-project/knowledge/releases/download/v1.12.0/knowledge.war

※環境は以下の通りです。
・Apache Tomcat/8.0.38

**Comment by koda-masaru** [comment]
This log is just information, and it is not error.
I Think It is your environmental reason that it does not to start up.
Please read online manual.

**Comment by koda-masaru** [comment]
このログはエラーではありません。
起動しないのは、ご利用の環境のせいだと思われますので、私では解析できません。
また、オンラインマニュアルを読んでみてください。

**Comment by naotoshin** [comment]
@koda-masaru 

早々のご確認をありがとうございます。
情報を小出しにしてしまって申し訳ありません。

上記の事象は、もともとv1.7.0のアプリケーションをデプロイしていたところ、warファイルを最新バージョンのアプリケーションで上書きしてアップデートしようとしていた際に発生しています。

また、先ほど再度試してみて、本日(2018/3/1)時点のログ `localhost.2018-03-01.log` を確認したところ、以下のエラーメッセージが出力されていました。

```
01-Mar-2018 01:34:31.960 SEVERE [localhost-startStop-5] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.support.project.knowledge.deploy.InitializationListener
 org.support.project.ormapping.exception.ORMappingException: ERROR: relation "service_configs" does not exist
  Position: 15 [cause] ERROR: relation "service_configs" does not exist
  Position: 15
----- SQL Infomation -----
[sql]SELECT * FROM SERVICE_CONFIGS WHERE SERVICE_NAME = ?  AND DELETE_FLAG = 0
[params]
	[params][0]knowledge
[execute]SELECT * FROM SERVICE_CONFIGS WHERE SERVICE_NAME = knowledge  AND DELETE_FLAG = 0

	at org.support.project.ormapping.dao.AbstractDao.executeQueryOnKey(AbstractDao.java:359)
	at org.support.project.ormapping.dao.AbstractDao.executeQuerySingle(AbstractDao.java:426)
	at org.support.project.knowledge.dao.ServiceConfigsDao_$$_jvst8e5_3._d16executeQuerySingle(ServiceConfigsDao_$$_jvst8e5_3.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.aop.Intercepter.invoke(Intercepter.java:182)
	at org.support.project.knowledge.dao.ServiceConfigsDao_$$_jvst8e5_3.executeQuerySingle(ServiceConfigsDao_$$_jvst8e5_3.java)
	at org.support.project.knowledge.dao.gen.GenServiceConfigsDao.selectOnKey(GenServiceConfigsDao.java:156)
	at org.support.project.knowledge.dao.ServiceConfigsDao_$$_jvst8e5_3._d49selectOnKey(ServiceConfigsDao_$$_jvst8e5_3.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.aop.Intercepter.invoke(Intercepter.java:174)
	at org.support.project.knowledge.dao.ServiceConfigsDao_$$_jvst8e5_3.selectOnKey(ServiceConfigsDao_$$_jvst8e5_3.java)
	at org.support.project.knowledge.logic.ServiceConfigLogic.load(ServiceConfigLogic.java:33)
	at org.support.project.knowledge.logic.ServiceConfigLogic_$$_jvst8e5_2._d6load(ServiceConfigLogic_$$_jvst8e5_2.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.support.project.aop.Intercepter.invoke(Intercepter.java:192)
	at org.support.project.knowledge.logic.ServiceConfigLogic_$$_jvst8e5_2.load(ServiceConfigLogic_$$_jvst8e5_2.java)
	at org.support.project.knowledge.deploy.InitializationListener.contextInitialized(InitializationListener.java:74)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "service_configs" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at org.support.project.ormapping.dao.AbstractDao.executeQueryOnKey(AbstractDao.java:351)
	... 40 more
```

DB上に必要な環境変数がないことが原因でしょうか？

**Comment by naotoshin** [comment]
@koda-masaru 

上記、解決しました。

tomcatの設定ファイル `/usr/local/tomcat/conf/tomcat8.conf`の最後に以下の記述を追加致しました。

```
  KNOWLEDGE_HOME="/usr/share/tomcat8/.knowledge"
```

こちら、インストール手順やマニュアルに相当する記述はありますでしょうか？
無いようでしたら適宜追加していただきたく。

**Comment by koda-masaru** [comment]
@naotoshin

回答できずにすみません。

v1.7.0は動いていたのですよね？
それを v1.12.0 にバージョンアップしたら、「KNOWLEDGE_HOME」の環境変数が無いために起動出来なかったということであっていますか？

「KNOWLEDGE_HOME」の環境変数については、 https://information-knowledge.support-project.org/backup-ja あたりに少し説明を書いています。

おかしいのは、v1.7.0が動いていた環境に、v1.12.0にしても、「KNOWLEDGE_HOME」を設定しなくても動くはずなのです。
「KNOWLEDGE_HOME」の指定がなければ、ホームディレクトリに「.knowledge」という名前でアクセス先が決まるので。

もしかすると、Knowledgeのバージョンアップ時に、Tomcatのバージョンアップや起動ユーザの変更など、環境面の変更も同時に行ったのではないでしょうか？
それだと、今まで動いていたデータが見つけられないのは当たり前なので説明がつくのですが。

**Comment by sage-git** [comment]
自分の環境ですが、knowledge 1.13.0を新規にインストールするにあたり、KNOWLEDGE_HOME の設定を忘れていたところ、tomcat9だと

```
Env [KNOWLEDGE_HOME] was not found.
ESC[2;36m INFOESC[m 2019-08-21 04:59:40,229 GlobalInitializationListener(36) [APP LOG] /home/tomcat/.knowledge/logs
/app.log
ESC[2;36m INFOESC[m 2019-08-21 04:59:40,747 H2DBServerLogic(51) H2 Database server started.
ESC[2;36m INFOESC[m 2019-08-21 04:59:40,938 Intercepter(218) [ERROR] class org.support.project.web.dao.SystemsDao_$
$_jvst790_0 : selectOnKey : javax/xml/bind/JAXBException
ESC[2;36m INFOESC[m 2019-08-21 04:59:40,940 Intercepter(220)   <Cause>
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
（以下略）
```

と出て起動しませんでした。

tomcat8をインストールしなおすと問題なく起動し、/home/tomcat/（tomcat起動ユーザー）以下に.knowledgeが生成されているのを確認しました。

今回は過去のデータがない新規のインストールで起こった現象ですので、tomcatのバージョン依存の問題なのでは、と推測します。

Google cloud platformのVM上で動くubuntu 18.04 LTS minimalで、knowledgeを試してみようと１からインストールしたときの現象です。
tomcatはaptではなく、公式からbinのtar.gzを落として/usr/local以下に展開し、serviceなど設定ファイルは手で編集しました。

**Comment by sage-git** [comment]
すみません。こちらで自分の環境でも動かないとメッセージをコメントしたものですが、Javaのバージョンの問題でした。メッセージを削除しておきます。
