### ISSUE TITLE
詳細なメール送信エラー

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#143]
Gmailアカウントでのメール送信はできているのですが、
他のSMTPサーバで送信しようとしたところエラーとなり送信できませんでした。

```
ERROR 2015-11-11 17:04:32,901 [MailSendBat(189)] Mail send error
javax.mail.AuthenticationFailedException: 535 5.7.0 authentication failed

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:826)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:761)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:685)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.support.project.knowledge.bat.MailSendBat.mailSend(MailSendBat.java:178)
        at org.support.project.knowledge.bat.MailSendBat.start(MailSendBat.java:93)
        at org.support.project.knowledge.bat.MailSendBat.main(MailSendBat.java:63)
```

KnowledgeサーバからSMTPサーバへの接続はできているようなので、Knowledgeの認証エラーログをもとに状況を確認したいと考えています。
上記よりもさらに詳細なログを出力していただくことは可能でしょうか。

メール送信テスト機能 #98 でも詳細なログが確認できると有益かと思います。

---

mail.debug = trueを設定するとさらに詳細なデバッグログが得られる？

http://blog.olivinecafe.info/post/104148110795/javamail%E3%81%A7%E3%83%A1%E3%83%BC%E3%83%AB%E9%80%81%E4%BF%A1

```
properties.setProperty("mail.debug", "true");
```

**Comment by irgaly** [comment]
すみません。エラーの原因はSMTPアカウントの間違いでした...
正しいアカウント情報で、Gmailではないサーバでも正常にメール送信できることを確認できました。

どの設定に間違いがあるかというのが判別できるのであれば、詳細なエラー内容の出力は有益かと思います。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

私も自分のチームで導入している環境も、メール送信のセットアップで苦労しました。
（その時は、ポートの設定を間違えていただけでした。。。）

このため、 #98 のメール送信テスト機能は実現したい機能の一つと思っています。
それを実現する際に、上記のメール送信の詳細ログの出力も導入しようと思います。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
