### ISSUE TITLE
Cookieに使用してはいけない文字が含まれている

### ISSUE THREAD

**Issue by carme-264pp** [support-project/knowledge#164]
KNOWLEDGE_HISTORYの値にカンマを使用されているようですが、Cookieの値にはカンマは使用できないようです。

Tomcat 9.0.0.M1で実行させたところ、Tomcat内部でのCookieチェックの際にIllegalArgumentExceptionがスローされる問題が発生しています。
> Caused by: java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:160)
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:109)
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:960)
	at org.apache.catalina.connector.Response.addCookie(Response.java:908)
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:391)
	at org.support.project.knowledge.control.open.KnowledgeControl.view(KnowledgeControl.java:111)
	... 35 more

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
初歩的なミスをしまいまいた。
次回のリリースまでに修正したいと思います。

**Comment by carme-264pp** [comment]
対応ありがとうございます。

**Comment by koda-masaru** [comment]
次回のリリースに含まれますので、ご確認ください。
他にも何かあれば、お気軽にissue登録してくださいね。

**Comment by koda-masaru** [comment]
v0.7.0を正式にリリース済み。いったん本issueはクローズします。

**Comment by carme-264pp** [comment]
確認のお返事が遅れてしまってすみません。
Tomcat 9.0.0 M1環境にv0.7.0pre2をデプロイし、記事をいくつか閲覧しても例外が発生しないことを確認しました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
無事に動いたようで安心しました。

また何かありましたら、ご連絡願います。
