### ISSUE TITLE
しばらく使っているとInternal Server Errorが出る

### ISSUE THREAD

**Issue by yoshimov** [support-project/knowledge#18]
どういう条件かまだわかりませんが、こちらの環境でしばらく使っていると、Internal Server Errorになることがあります。
Tomcatを再起動すると直ります。

## 環境

- Knowledge 0.4.5
- Ubuntu 14.10
- Docker 1.3.1
- Tomcat 8.0.9
- OpenJDK 1.8.0_40

## エラーログ

以下はノウハウ一覧を表示しようとした際のエラーログです。

<pre>
ERROR 2015-03-11 00:02:30,970 [Transaction(41)] Error(Rollback) : org.support.project.knowledge.dao.KnowledgesDao_$$_jvst838_2#_d44selectKnowledges
ERROR 2015-03-11 00:02:30,976 [Transaction(45)] Error
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalArgumentException"; SQL statement:
COMMIT [50000-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.command.Command.executeUpdate(Command.java:262)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:345)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at org.h2.mvstore.Page$PageChildren.read(Page.java:1040)
	at org.h2.mvstore.MVStore.readPageChunkReferences(MVStore.java:1267)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1240)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1244)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1244)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1227)
	at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1186)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:980)
	at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:970)
	at org.h2.mvstore.MVStore.commit(MVStore.java:931)
	at org.h2.mvstore.db.TransactionStore.endTransaction(TransactionStore.java:450)
	at org.h2.mvstore.db.TransactionStore.commit(TransactionStore.java:348)
	at org.h2.mvstore.db.TransactionStore$Transaction.commit(TransactionStore.java:762)
	at org.h2.engine.Session.commit(Session.java:492)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	... 3 more

	at org.h2.engine.SessionRemote.done(SessionRemote.java:622)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:191)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:468)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.commit(PoolableConnectionWrapper.java:91)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.commit(PoolableConnectionWrapper.java:91)
	at org.support.project.ormapping.transaction.TransactionPool.commit(TransactionPool.java:98)
	at org.support.project.ormapping.transaction.TransactionManager.commit(TransactionManager.java:33)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:36)
	at org.support.project.knowledge.logic.KnowledgeLogic.getKnowledgeDatas(KnowledgeLogic.java:421)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:264)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:318)
	at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:170)
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:130)
	at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:83)
	at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:349)
	at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:32)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
ERROR 2015-03-11 00:02:30,983 [Transaction(46)] Error
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Transaction is closed [1.4.183/4]"; SQL statement:
ROLLBACK [50000-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.command.Command.executeUpdate(Command.java:262)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:345)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Transaction is closed [1.4.183/4]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:768)
	at org.h2.mvstore.db.TransactionStore$Transaction.checkNotClosed(TransactionStore.java:804)
	at org.h2.mvstore.db.TransactionStore$Transaction.commit(TransactionStore.java:761)
	at org.h2.engine.Session.rollback(Session.java:575)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	... 3 more

	at org.h2.engine.SessionRemote.done(SessionRemote.java:622)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:191)
	at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1501)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:489)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.rollback(PoolableConnectionWrapper.java:95)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.rollback(PoolableConnectionWrapper.java:95)
	at org.support.project.ormapping.transaction.TransactionPool.rollback(TransactionPool.java:106)
	at org.support.project.ormapping.transaction.TransactionManager.rollback(TransactionManager.java:38)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:43)
	at org.support.project.knowledge.logic.KnowledgeLogic.getKnowledgeDatas(KnowledgeLogic.java:421)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:264)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:318)
	at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:170)
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:130)
	at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:83)
	at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:349)
	at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:32)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
INFO  2015-03-11 00:02:30,985 [Intercepter(220)] [ERROR] class org.support.project.knowledge.dao.KnowledgesDao_$$_jvst838_2 : selectKnowledges : General error: "java.lang.IllegalArgumentException"; SQL statement:
COMMIT [50000-183]
INFO  2015-03-11 00:02:30,986 [Intercepter(215)] error. [object]class org.support.project.knowledge.logic.KnowledgeLogic_$$_jvst838_1[proceed]_d15searchKnowledge[param0][param1]null[param2]0[param3]10
General error: "java.lang.IllegalArgumentException"; SQL statement:
COMMIT [50000-183]
ERROR 2015-03-11 00:02:30,989 [ControlManagerFilter(195)] ERROR SEND
ERROR 2015-03-11 00:02:30,991 [LoggingFilter(63)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:199)
	... 25 more
Caused by: org.support.project.common.exception.SystemException: 
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:134)
	at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:83)
	at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:349)
	at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:32)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:173)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:130)
	... 35 more
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalArgumentException"; SQL statement:
COMMIT [50000-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.command.Command.executeUpdate(Command.java:262)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:345)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at org.h2.mvstore.Page$PageChildren.read(Page.java:1040)
	at org.h2.mvstore.MVStore.readPageChunkReferences(MVStore.java:1267)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1240)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1244)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1244)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1227)
	at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1186)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:980)
	at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:970)
	at org.h2.mvstore.MVStore.commit(MVStore.java:931)
	at org.h2.mvstore.db.TransactionStore.endTransaction(TransactionStore.java:450)
	at org.h2.mvstore.db.TransactionStore.commit(TransactionStore.java:348)
	at org.h2.mvstore.db.TransactionStore$Transaction.commit(TransactionStore.java:762)
	at org.h2.engine.Session.commit(Session.java:492)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	... 3 more

	at org.h2.engine.SessionRemote.done(SessionRemote.java:622)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:191)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:468)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.commit(PoolableConnectionWrapper.java:91)
	at org.support.project.ormapping.connection.PoolableConnectionWrapper.commit(PoolableConnectionWrapper.java:91)
	at org.support.project.ormapping.transaction.TransactionPool.commit(TransactionPool.java:98)
	at org.support.project.ormapping.transaction.TransactionManager.commit(TransactionManager.java:33)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:36)
	at org.support.project.knowledge.logic.KnowledgeLogic.getKnowledgeDatas(KnowledgeLogic.java:421)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:264)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:318)
	at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:170)
	... 36 more
</pre>

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

コネクションプールあたりが、エラーになっていそうですが、
はっきり原因がわかりません。
後でデバッグしてみます。

**Comment by koda-masaru** [comment]
トランザクション管理とコネクションプールのあたりで、
それっぽいところを見つけたので修正中です。

**Comment by koda-masaru** [comment]
いったん修正終わりです。
ただ、現象が再現できなかったので、リリースをしてみて、しばらく様子をみようと思います。

**Comment by koda-masaru** [comment]
しばらく動かしてみた感じでは、発生しない（？）ので、いったんリリースしました
