### ISSUE TITLE
検索時にエラーが発生する事がある

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#257]
ブログのコメントへの投稿から

----

続けて別件、ご報告いたします。（※Release v1.0.0 で動作検証）

Knowledgeの木ワード検索として、[秋葉原]を入力→検索を行うと、Server Error
が表示され、検索が正常に行われません。[秋葉原]以外の語は今のところ問題ありません。

```
INFO 2016-01-25 10:03:49,765 [Intercepter(215)] error. [object]class org.support.project.knowledge.logic.KnowledgeLogic_$$_jvst929_5[proceed]_d21searchKnowledge[param0]秋葉原[param1]null[param2]null[param3]org.support.project.web.bean.LoginedUser@48783cda[param4]0[param5]50
[throwable.getMessage()] null
ERROR 2016-01-25 10:03:49,769 [ControlManagerFilter(206)] ERROR SEND
ERROR 2016-01-25 10:03:49,771 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException:
at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:319)
.
.（40行ほど略）
.
Caused by: java.lang.reflect.InvocationTargetException
at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:130)
... 34 more
Caused by: java.lang.NullPointerException
at org.support.project.knowledge.logic.KnowledgeLogic.getKnowledgeDatas(KnowledgeLogic.java:708)
at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:438)
```

----

**Comment by koda-masaru** [comment]
「秋葉原」のキーワードのエラーですが、データが不整合になっていると思います。（不整合になるような不具合があるのかも？）

具体的には、Knowledgeの検索は、以下の順序でデータ取得しています。
①全文検索エンジンで対象の情報を取得
②その情報に対し、RDBから付加情報（名称など）を付与

その中で、①で「秋葉原」のキーワードでヒットするナレッジがあったのですが、②のRDBから付加情報を取得する際にエラーになっているように思えます。

データ不整合が、どのような条件で発生するのか、調査してみます。

**Comment by koda-masaru** [comment]
上記のような条件ですので、キーワードの「秋葉原」が悪いのではなく、そのキーワードでヒットするデータが不整合になる事が問題かと思います。
（私の環境では「秋葉原」はエラーになりませんので）

**Comment by koda-masaru** [comment]
全文検索エンジンはRDBのトランザクション制御の中にあるわけでは無いので、
データが不整合になることを完全には回避できない。
そこで、不整合状態になった場合でもエラーにならないように修正しておく。

**Comment by koda-masaru** [comment]
Release v1.1.0 リリースしました
