### ISSUE TITLE
RDSへの接続エラー

### ISSUE THREAD

**Issue by tatsu07** [support-project/knowledge#283]
現在AWS上にknowledgeを構築し、DBはRDSを使用しようと考えております。
GUI上から設定を試みたところ下記のようなエラーが発生しました。

```
ERROR 2016-02-08 18:51:29,946 [ConnectionPoolImpl(129)] Can't create a new connection for {rds endpoint}
java.sql.SQLException: No suitable driver found for {rds endpoint}
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.support.project.ormapping.connection.ConnectionPoolImpl.newConnection(ConnectionPoolImpl.java:124)
        at org.support.project.ormapping.connection.ConnectionPoolImpl.getCon(ConnectionPoolImpl.java:106)
        at org.support.project.ormapping.connection.ConnectionPoolImpl.getConnection(ConnectionPoolImpl.java:66)
        at org.support.project.ormapping.connection.ConnectionPoolImpl.getConnection(ConnectionPoolImpl.java:60)
        at org.support.project.ormapping.connection.ConnectionManager.checkConnectionConfig(ConnectionManager.java:96)
        at org.support.project.knowledge.control.admin.DatabaseControl.custom_save(DatabaseControl.java:196)
        at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:130)
        at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:83)
        at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:360)
        at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:32)
        at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:184)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:79)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:312)
        at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:91)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1080)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:75)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:757)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

ちなみに構成はprivate networkに構築しており、psqlコマンド経由では接続出来ております。

ご教授の程、よろしくお願いします。

**Comment by koda-masaru** [comment]
エラーの内容を見ると、PostgreSQLのJDBCドライバが見つからないというエラーかと思います。
ただ、KnowledgeのWEB-INF/libに、PostgreSQLのJDBCは追加しているはずなので、
なぜ見つけられないのかがわかりません。
他にエラーが発生している部分は無いでしょうか？

**Comment by tatsu07** [comment]
すみません、お恥ずかしながら、JDBCでしたね...
URLという単語でエンドポイント(ホスト名)のみ入力してました。
jdbcスキーマ名から入力したところ、保存できました

```
jdbc:postgresql://host:port/database
```

placeholderにサンプルURL等あれば尚親切かなと思うので、ご検討頂ければと思います。

**Comment by koda-masaru** [comment]
解決できてよかったです :smile: 

> placeholderにサンプルURL等あれば尚親切かなと思うので、ご検討頂ければと思います。

そうですね。
placeholderにサンプルを記載しようと思います。
あと、マニュアルをだんだんと整備していきますね。

**Comment by koda-masaru** [comment]
https://github.com/support-project/knowledge/issues/289

にissueを登録しました。本issueは、解決できたようですのでクローズしますね。
