### ISSUE TITLE
データのエクスポートでエラー

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#446]
デモサイトの投稿から

---

エクスポートは私の環境では「Internal Server Error」と表示され確認ができず
両者の違いがわかりません。

問い合わせをどこにすればよいのかわからず書き込んでしまいました。
すみません。

ちなみにエクスポートのエラーは以下の内容です。

```
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException:
at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:309)
at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:94)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:780)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException:
at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:214)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:302)
... 25 more
Caused by: org.support.project.common.exception.SystemException:
at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:136)
at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:106)
at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:360)
at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:31)
at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:181)
... 31 more
Caused by: java.lang.reflect.InvocationTargetException
at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:132)
... 35 more
Caused by: java.io.FileNotFoundException: C:\Windows\system32\config\systemprofile.knowledge\tmp\DataExport.zip (指定されたファイルが見つかりません。)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.(FileInputStream.java:138)
at org.support.project.knowledge.control.admin.DatabaseControl.download(DatabaseControl.java:403)
... 36 more


```

**Comment by KeithK0720** [comment]
転記ありがとうございました。
エラーについて何か確認すべきところがあれば教えてください。
（環境など提示すべき事なども）

**Comment by koda-masaru** [comment]
ありがとうございます。
WindowsでKnowledgeのサービスを動作させているかと思いますが、
以下の情報を教えていただけると助かります。

- OS
- Javaのバージョン
- Tomcat（もしくはJettyなど）のバージョン

**Comment by KeithK0720** [comment]
遅くなってすみませんが、確認しました。
- OS: Windows 7 professional sp1
- Javaのバージョン: 1.8.0_101
- Tomcat（もしくはJettyなど）のバージョン: 8.5.4

**Comment by koda-masaru** [comment]
ありがとうございます。再現調査してみます。

**Comment by koda-masaru** [comment]
（作業メモ）
よくよくログを見てみると、パスがおかしい気がする。

```
C:\Windows\system32\config\systemprofile.knowledge\tmp\DataExport.zip
```

正しくは、

```
C:\Windows\system32\config\systemprofile\.knowledge\tmp\DataExport.zip
```

にならないと動かないと思われる。

エクスポート処理の中の、テンポラリディレクトリ生成の処理を見直す。

**Comment by koda-masaru** [comment]
現象を再現させることが出来ない。
とりあえず、様子見か。

**Comment by m-onda** [comment]
koda様、
とても便利なツールのご提供有難う御座います。便利に使わせてもらっております。
実は、私の環境でも本issueと同様な現象が起こりました。そこで再現性についてわかったことを投稿させていただきます。参考になれば幸いです。
以下、再現するパターンと、再現しないパターンの両方を記載させて頂きます。
## 再現するパターン：
  1. Ubuntu16.04にjava1.8.0_121, tomcat8.0.39, knowledge1.8.1を設置
  2. databaseをpostgres9.5.6を使うように設定
  3. ReverseProxy(nginx)で```https://リバースプロキシーサーバー/knowledge```でアクセスできるように設定
  4. ```https://リバースプロキシーサーバー/knowledge``` でアドミン権限でログイン
  5. （一応）記事をひとつ投稿
  6. 「システムメニュー」の「エクスポート」を実行
エクスポートを実行するも、実施のエクスポートファイルの生成が行われていないか、あるいは、削除されてしまっているようです。実際にファイルが無いことは目視確認しました。

## 再現しないパターン
  1. 上記「再現するパターン」で、knoledgeサービスに直接ログイン。具体的には、```http://knowledheサーバー:8080/knowledge``` でアドミン権限でログイン
  2. （一応）記事をひとつ投稿
  3. 「システムメニュー」の「エクスポート」を実行
この場合ですと、エクスポートファイルが正しく作成され、ダウンロードして保存することができます。
以上、追加情報など必要でしたら、なんなりとお知らせください。
宜しくお願いいたします。

**Comment by koda-masaru** [comment]
@m-onda さま
情報ありがとうございます。いただいた情報を元に後で調べてみます。
（年度初めで解析の時間がとれそうに無いので、少々お待ち下さい。）

**Comment by Monota** [comment]
同画面は WebSocket を利用しているので、Nginx が WebSocket をハンドリングできるように設定されていれば Reverse Proxy 環境下で発生しなくなると思います。http://nginx.org/en/docs/http/websocket.html あたりを参考にしてください。

**Comment by Monota** [comment]
```
Caused by: java.io.FileNotFoundException: C:\Windows\system32\config\systemprofile.knowledge\tmp\DataExport.zip
```

についてですが、Windows に Tomcat を Installer でインストールした場合、仮にファイルパスが正しくても、サービスがローカルシステムアカウントで動作するため、Knowledge から java を kick できないので動かないと思います。

```
java.io.IOException: Cannot run program "java" (in directory "C:\WINDOWS\system32\config\systemprofile\.knowledge\logs"): CreateProcess error=2, 指定されたファイルが見つかりません。
```

このため Export するファイルが作れずに FileNotFound になっていると思います。Windows Server には詳しくないのでどう運用するのがいいかはわかりませんが、ローカルシステムアカウントで動作させずに java にパスが通っているローカルアカウントで動作させると java を kick できるようになり、エクスポート等、動くかもしれません。

![image](https://cloud.githubusercontent.com/assets/9009605/25757453/846f3098-3205-11e7-9f3f-adcf5e8a003b.png)

これが Installer で Tomcat をインストールした直後のサービスの設定です。

**Comment by koda-masaru** [comment]
@Monota さん
情報ありがとうございます。
たしかに Reverse Proxy を使う場合、Websocketが使える必要があります。
また、`java` にパスが通っていないと動かないというのも、そのとおりです。
後で、マニュアルの方に追記しようと思います。

@m-onda さん
再現した環境の Nginx で Websocketが使えない設定になっていましたでしょうか？
Nginxだと、デフォルトでWebsocketは使えるような気もするのですが。

**Comment by koda-masaru** [comment]
I think that there is no problem, so close this Issue.
