### ISSUE TITLE
PostgreSQL設定後のSQLエラー

### ISSUE THREAD

**Issue by husky774rr** [support-project/knowledge#491]
knowledgeを使用する為に新規環境を構築しましたが下記の通り問題が発生して困っています。
対応方法等をご教示いただけないでしょうか。
# 現象

Knowledgeを新規導入後、PostgreSQL接続設定まで完了。
Top画面(knowledge/open.knowledge/list)へアクセスするとServerErrorが発生する。
# 環境
- OS:CentOS6.8
- Java:1.8.0_101
- PostgreSQL:8.4.20
- Apache Tomcat:8.5.5
- Knowledge:Release v1.5.0
# エラー詳細
## エラー内容詳細

エラーログによるとSQLのSELECT句に指定された「TAGS.*」に関するGROUPBY句が無いよ。
とのことでSQLを確認するとエラーログどおりだった。
そこで、エラー発生SQLをエラー修正SQLの通り修正しpsqlから直接実行したところ問題なく結果が得られた。

この結果からSQLに問題があると考えるものの、
多くのユーザに運用そして利用していることを考えると
おそらく環境や設定等に問題があるのではないかと推測。
## エラー発生SQL

```
SELECT TAGS.*, COUNT(KNOWLEDGE_TAGS.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT FROM TAGS
INNER JOIN KNOWLEDGE_TAGS ON (TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID)
WHERE  EXISTS (
    SELECT KNOWLEDGES.KNOWLEDGE_ID FROM KNOWLEDGES
    INNER JOIN KNOWLEDGE_USERS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_USERS.KNOWLEDGE_ID)
    LEFT OUTER JOIN KNOWLEDGE_GROUPS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_GROUPS.KNOWLEDGE_ID)
    WHERE KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
    AND KNOWLEDGES.DELETE_FLAG = 0
    AND (
            KNOWLEDGE_USERS.USER_ID IN (0, -2147483648)
            OR
            KNOWLEDGE_GROUPS.GROUP_ID IN (-1)
    )
)
AND TAGS.DELETE_FLAG = 0
GROUP  BY TAGS.TAG_ID
ORDER  BY KNOWLEDGE_COUNT DESC, TAG_NAME
LIMIT  10 OFFSET 0;
```
## エラー修正SQL

/\* Add Start _/から/_ Add End */までのグルーピングを追加

```
SELECT TAGS.*,COUNT(KNOWLEDGE_TAGS.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT FROM TAGS
INNER JOIN KNOWLEDGE_TAGS ON (TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID)
WHERE  EXISTS (
    SELECT KNOWLEDGES.KNOWLEDGE_ID FROM KNOWLEDGES
    INNER JOIN KNOWLEDGE_USERS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_USERS.KNOWLEDGE_ID)
    LEFT OUTER JOIN KNOWLEDGE_GROUPS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_GROUPS.KNOWLEDGE_ID)
    WHERE  KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
    AND KNOWLEDGES.DELETE_FLAG = 0
    AND (
            KNOWLEDGE_USERS.USER_ID IN (0, -2147483648)
            OR
            KNOWLEDGE_GROUPS.GROUP_ID IN (-1)
    )
)
AND TAGS.DELETE_FLAG = 0
GROUP BY TAGS.TAG_ID /* Add START */, TAGS.TAG_NAME, TAGS.INSERT_USER, TAGS.INSERT_DATETIME, TAGS.UPDATE_USER, TAGS.UPDATE_DATETIME, TAGS.DELETE_FLAG /* Add END */
ORDER BY KNOWLEDGE_COUNT DESC,TAG_NAME
LIMIT  10 OFFSET 0;
```
## エラー発生箇所Java

[org.support.project.knowledge.dao.TagsDao.selectWithKnowledgeCount(TagsDao.java:123)](https://github.com/support-project/knowledge/blob/master/src/main/java/org/support/project/knowledge/dao/TagsDao.java)
## エラー発生箇所SQL

[/org/support/project/knowledge/dao/sql/TagsDao/TagsDao_selectWithKnowledgeCount.sql](https://github.com/support-project/knowledge/blob/master/src/main/resources/org/support/project/knowledge/dao/sql/TagsDao/TagsDao_selectWithKnowledgeCount.sql)
## エラーログ

```
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:309)
    at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:94)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
    at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:476)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
    at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:214)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:193)
    ... 25 more
Caused by: org.support.project.common.exception.SystemException: 
    at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:136)
    at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:106)
    at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:360)
    at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:31)
    at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:181)
    ... 31 more
Caused by: java.lang.reflect.InvocationTargetException
    at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:132)
    ... 35 more
Caused by: org.support.project.ormapping.exception.ORMappingException: ERROR: 列"tags.tag_name"はGROUP BY句で出現しなければならないか、集約関数内で使用しなければなりません
  ポジション: 8 [cause] ERROR: 列"tags.tag_name"はGROUP BY句で出現しなければならないか、集約関数内で使用しなければなりません
  ポジション: 8
----- SQL Infomation -----
[sql]SELECT TAGS.*, COUNT(KNOWLEDGE_TAGS.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT FROM TAGS INNER JOIN KNOWLEDGE_TAGS ON (TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID) WHERE EXISTS ( SELECT KNOWLEDGES.KNOWLEDGE_ID FROM KNOWLEDGES INNER JOIN KNOWLEDGE_USERS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_USERS.KNOWLEDGE_ID) LEFT OUTER JOIN KNOWLEDGE_GROUPS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_GROUPS.KNOWLEDGE_ID) WHERE KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID AND KNOWLEDGES.DELETE_FLAG = 0 AND ( KNOWLEDGE_USERS.USER_ID IN (0,?) OR KNOWLEDGE_GROUPS.GROUP_ID IN (?) ) ) AND TAGS.DELETE_FLAG = 0 GROUP BY TAGS.TAG_ID ORDER BY KNOWLEDGE_COUNT DESC, TAG_NAME LIMIT ? OFFSET ?  
[params]
    [params][0]-2147483648
    [params][1]-1
    [params][2]10
    [params][3]0
[execute]SELECT TAGS.*, COUNT(KNOWLEDGE_TAGS.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT FROM TAGS INNER JOIN KNOWLEDGE_TAGS ON (TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID) WHERE EXISTS ( SELECT KNOWLEDGES.KNOWLEDGE_ID FROM KNOWLEDGES INNER JOIN KNOWLEDGE_USERS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_USERS.KNOWLEDGE_ID) LEFT OUTER JOIN KNOWLEDGE_GROUPS ON (KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGE_GROUPS.KNOWLEDGE_ID) WHERE KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID AND KNOWLEDGES.DELETE_FLAG = 0 AND ( KNOWLEDGE_USERS.USER_ID IN (0,-2147483648) OR KNOWLEDGE_GROUPS.GROUP_ID IN (-1) ) ) AND TAGS.DELETE_FLAG = 0 GROUP BY TAGS.TAG_ID ORDER BY KNOWLEDGE_COUNT DESC, TAG_NAME LIMIT 10 OFFSET 0  

    at org.support.project.ormapping.dao.AbstractDao.executeQuery(AbstractDao.java:402)
    at org.support.project.ormapping.dao.AbstractDao.executeQueryList(AbstractDao.java:440)
    at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
    at org.support.project.knowledge.dao.TagsDao.selectWithKnowledgeCount(TagsDao.java:123)
    at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
    at org.support.project.knowledge.logic.TagLogic.selectTagsWithCount(TagLogic.java:44)
    at org.support.project.knowledge.control.open.KnowledgeControl.setSublistInformations(KnowledgeControl.java:247)
    at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:449)
    ... 36 more
Caused by: org.postgresql.util.PSQLException: ERROR: 列"tags.tag_name"はGROUP BY句で出現しなければならないか、集約関数内で使用しなければなりません
  ポジション: 8
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:562)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
    at org.support.project.ormapping.dao.AbstractDao.executeQuery(AbstractDao.java:393)
    ... 43 more

```
# 補足

組み込みDBでは問題なく動作することを確認済み。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
上の修正を反映していこうと思います。

ただ、PostgreSQLですが、動作確認を行っているバージョンは、現在は9.4系 (9.4.9) になっております。（開発開始時点の最新版が9.4系だったので）
たぶん9.4系であれば、上記の修正をしないでも動くと思います。
8.4.20ですと、その他の部分でもエラーが発生することがあるかもしれませんので、できれば
DBのバージョンアップをご検討ください。

**Comment by husky774rr** [comment]
早速ご回答いただきありがとうございます。
PostgreSQLはバージョンアップ可能な環境なので9.4にバージョンアップして確認してみます。

また結果を報告します。

**Comment by husky774rr** [comment]
PostgreSQL Version 9.6 にて正常に動作することを確認しました。
これから現場投入へ向けて使用方法を学習します。

最後に、もしどこかに記載済であれば申し訳ないのですが、
動作確認済環境、推奨環境(各種ミドルウェア群のバージョン)を明文化していただければ、
新規環境構築の際、参考になるかと思います。

**Comment by koda-masaru** [comment]
そうですね。
インストールマニュアルに、動作確認環境や推奨環境を書いていこうと思います。
作るのに時間をかけているので、マニュアルなどの整備が進んでおらず、すみません。

**Comment by koda-masaru** [comment]
#515 に新たなissueとして登録しました。
本issueは、いったん解決済としてクローズいたします。
