### ISSUE TITLE
トップページが表示されない

### ISSUE THREAD

**Issue by shiratsu** [support-project/knowledge#550]
はじめまして。
お世話になります。
以下のページを参考にセットアップをしているのですが、うまく行きません。
https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)

インストールまでは多分出来てるのですが、アクセスすると、404になります。

<img width="1103" alt="2016-12-29 22 06 59" src="https://cloud.githubusercontent.com/assets/918490/21544570/850987ac-ce13-11e6-87f2-21a8b2b93485.png">

私の環境は、amazon_linuxのt2.microを使っており、
```
[ec2-xxxxxx@xxxxxx webapps]$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
[ec2-xxxxxx@xxxxxx webapps]$ javac -version
javac 1.8.0_111
[ec2-xxxxxx@xxxxxx webapps]$
```
tomcatはソースからインストールしました。
何が問題なのでしょうか。

よろしくお願いいたします。

**Comment by koda-masaru** [comment]
Tomcatの起動は成功しているのですが、Knowledgeのデプロイができてないように思います。
ただ、上の情報だけだと、はっきりとはわかりません。
Tomcat/logsにcatalina.outというログががあると思いますが、そのログが参照できればもう少しはっきりしますので、よければその情報を教えて下さい。

**Comment by shiratsu** [comment]
了解致しました。確認してみます。

**Comment by shiratsu** [comment]
```
for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /app.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1006)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.support.project.common.log.impl.log4j.Log4jLogInitializerImpl.createLog(Log4jLogInitializerImpl.java:11)
	at org.support.project.common.log.LogFactory.getLog(LogFactory.java:44)
	at org.support.project.web.websocket.EndpointConfigurator.<clinit>(EndpointConfigurator.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.tomcat.websocket.server.WsServerContainer.addEndpoint(WsServerContainer.java:219)
	at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:120)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
log4j:ERROR Either File or DatePattern options are not set for appender [APP_FILEOUT].
Env [KNOWLEDGE_HOME] was not found.
INFO  2016-12-30 23:30:51,665 [GlobalInitializationListener(37)] [APP LOG] /home/tomcat8/.knowledge/logs/app.log
```

**Comment by shiratsu** [comment]
上記のように出力されます
app.logとは、tomcat8ユーザの下にフォルダを作るり、パーミッションを与えるということでしょうか

**Comment by koda-masaru** [comment]
Knowledgeは、Tomcatの起動ユーザのホームディレクトリに「.knowledge」というフォルダを作成し、その中にデータを格納します。
ログを見ると、/app.logとなっているので、tomcatの起動ユーザにホームディレクトリの指定が設定されていないのでは無いでしょうか？

データディレクトリは、環境変数に KNOWLEDGE_HOME というキーで、ディレクトリのパスを指定する事で変更することが可能です。

データディレクトリを指定後、起動ユーザがそのディレクトリにアクセスできるように、writeのパーミッションを指定してください。

参考: https://support-project.org/knowledge_info/open.manual/page/backup

**Comment by shiratsu** [comment]
tomcatの起動方法を
```
sudo service tomcat start
```
から
```
sudo -u tomcat8 /usr/local/tomcat8/bin/startup.sh
```
に変更したところ

エラーは出なくなり、tomcatは動いてるようなのですが、、、
tomcatホームすら表示されなくなり、knowledgeのページも同様に表示されません。
```
01-Jan-2017 13:02:49.464 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /usr/local/tomcat8/webapps/knowledge.war
01-Jan-2017 13:03:01.769 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
INFO  2017-01-01 13:03:02,003 [GlobalInitializationListener(24)] Env [KNOWLEDGE_HOME] is [/home/tomcat8/.knowledge].
Env [KNOWLEDGE_HOME] was loaded. value is [/home/tomcat8/.knowledge].
INFO  2017-01-01 13:03:02,291 [GlobalInitializationListener(37)] [APP LOG] /home/tomcat8/.knowledge/logs/app.log
```

app.logも起動ユーザの直下にありません。
```
[ec2-user@xxxxxx webapps]$ sudo ls -la /home/tomcat8/
total 20
drwxr-xr-x 3 tomcat8 root    4096 Jan  1 12:43 .
drwxr-xr-x 4 root    root    4096 Dec 30 17:05 ..
-rw-r--r-- 1 tomcat8 tomcat8   47 Jan  1 12:43 .bashrc
drwxrw-rw- 3 tomcat8 tomcat8 4096 Dec 30 23:52 .knowledge
-rw------- 1 tomcat8 tomcat8 1613 Jan  1 12:43 .viminfo
```

これってどういう状況なのでしょうか。

**Comment by shiratsu** [comment]
ローカルのmacはうまくいってるので比較すると
```
INFO  2017-01-01 18:34:25,587 [InitializationListener(50)] knowledge install path: '/pathto/webapps/knowledge/'
INFO  2017-01-01 18:34:25,587 [InitializationListener(51)] knowledge home path: '/Users/xxxxx/.knowledge'
```
がないですね。。。

**Comment by shiratsu** [comment]
```
INFO  2017-01-01 22:35:17,290 [H2DBServerLogic(51)] H2 Database server started.
```
これが出力されないので、（上はmacローカルのcatalina.outから拾いました）なので、これが原因なのでしょうか

**Comment by shiratsu** [comment]
ec2はt2.microなのですが、小さすぎたりしますか？

**Comment by shiratsu** [comment]
https://support-project.org/knowledge/open.knowledge/view/365
こちらを参考にしてみたのですが、

```
org.support.project.common.exception.SystemException: IO Exception: "java.net.UnknownHostException: ip-xx-xx-xx-xx: ip-xx-xx-xx-xx: Name or service not known" [90028-183] [cause] IO Exception: "java.net.UnknownHostException: ip-xx-xx-xx-xx: ip-xx-xx-xx-xx: Name or service not known" [90028-183]
	at org.support.project.common.logic.H2DBServerLogic.start(H2DBServerLogic.java:54)
	at org.support.project.web.listener.H2DBManagerListener.contextInitialized(H2DBManagerListener.java:29)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: ip-xx-xx-xx-xx: ip-xx-xx-xx-xx: Name or service not known" [90028-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:287)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:268)
	at org.h2.server.TcpServer.getURL(TcpServer.java:201)
	at org.h2.tools.Server.start(Server.java:475)
	at org.support.project.common.logic.H2DBServerLogic.start(H2DBServerLogic.java:50)
	... 14 more
Caused by: java.net.UnknownHostException: ip-xx-xx-xx-xx: ip-xx-xx-xx-xx: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:266)
	... 17 more
Caused by: java.net.UnknownHostException: ip-xx-xx-xx-xx: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 18 more

```

こう出ますがどういうことなのでしょうか。

**Comment by shiratsu** [comment]
解決しました！
最終的にここが参考になりました！

https://confluence.atlassian.com/bamkb/bamboo-fails-on-startup-due-to-unknownhostexception-for-aws-private-ip-802170182.html

/etc/hostsをこうしました

```
127.0.0.1 localhost localhost.localdomain ip-xx-xx-xx-xx
```

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。無事に動いたようで安心しました。

↑の情報、私も知りませんでした。勉強になりました。ありがとうございます。
