### ISSUE TITLE
1.7.0へwarをアップデート後にknowledgeテーブルへのアクセスでエラー

### ISSUE THREAD

**Issue by tknr** [support-project/knowledge#595]
knowledge.war を更新しtomcat再起動後で
/knowledge/open.knowledge/list
へアクセス時に以下のexception

```
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
	at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:745)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:216)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:184)
	... 28 more
Caused by: org.support.project.common.exception.SystemException: 
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:136)
	at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:106)
	at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:345)
	at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:31)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:184)
	... 34 more
Caused by: java.lang.reflect.InvocationTargetException
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:132)
	... 38 more
Caused by: org.support.project.ormapping.exception.ORMappingException: 入出力例外: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390"
IO Exception: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390" [90031-183] [cause] 入出力例外: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390"
IO Exception: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390" [90031-183]
----- SQL Infomation -----

	at org.support.project.ormapping.common.ResultSetLoader.load(ResultSetLoader.java:133)
	at org.support.project.ormapping.dao.AbstractDao.load(AbstractDao.java:321)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.ormapping.dao.AbstractDao.load(AbstractDao.java:304)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.ormapping.dao.AbstractDao.executeQuery(AbstractDao.java:397)
	at org.support.project.ormapping.dao.AbstractDao.executeQueryList(AbstractDao.java:440)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.knowledge.dao.KnowledgesDao.selectKnowledges(KnowledgesDao.java:91)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
	at org.support.project.knowledge.logic.KnowledgeLogic.getKnowledgeDatas(KnowledgeLogic.java:678)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:467)
	at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:525)
	at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:442)
	... 39 more
Caused by: org.h2.jdbc.JdbcSQLException: 入出力例外: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390"
IO Exception: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 117390" [90031-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convertIOException(DbException.java:330)
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:302)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at org.support.project.ormapping.common.ResultSetLoader.load(ResultSetLoader.java:104)
	... 52 more
Caused by: java.io.IOException: org.h2.message.DbException: 入出力例外: "java.io.IOException: java.lang.NullPointerException"
IO Exception: "java.io.IOException: java.lang.NullPointerException" [90028-183]
	at org.h2.message.DbException.convertToIOException(DbException.java:364)
	at org.h2.store.LobStorageRemoteInputStream.read(LobStorageRemoteInputStream.java:73)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at org.h2.util.IOUtils.copyAndCloseInput(IOUtils.java:200)
	at org.h2.util.IOUtils.readStringAndClose(IOUtils.java:307)
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:292)
	... 54 more
Caused by: org.h2.message.DbException: 入出力例外: "java.io.IOException: java.lang.NullPointerException"
IO Exception: "java.io.IOException: java.lang.NullPointerException" [90028-183]
	at org.h2.message.DbException.convert(DbException.java:283)
	at org.h2.engine.SessionRemote.done(SessionRemote.java:629)
	at org.h2.engine.SessionRemote.readLob(SessionRemote.java:779)
	at org.h2.store.LobStorageRemoteInputStream.read(LobStorageRemoteInputStream.java:71)
	... 66 more
Caused by: org.h2.jdbc.JdbcSQLException: 入出力例外: "java.io.IOException: java.lang.NullPointerException"
IO Exception: "java.io.IOException: java.lang.NullPointerException" [90028-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:287)
	at org.h2.server.TcpServerThread.sendError(TcpServerThread.java:221)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:161)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.h2.message.DbException.convertToIOException(DbException.java:364)
	at org.h2.util.IOUtils.readFully(IOUtils.java:338)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:462)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.h2.mvstore.StreamStore$Stream.nextBuffer(StreamStore.java:453)
	at org.h2.mvstore.StreamStore$Stream.read(StreamStore.java:414)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.h2.server.TcpServerThread$CachedInputStream.read(TcpServerThread.java:551)
	at org.h2.util.IOUtils.readFully(IOUtils.java:329)
	... 3 more

	at org.h2.engine.SessionRemote.done(SessionRemote.java:622)
	... 68 more
```

関係あるかどうかは不明ですが、ログに出ていたh2 sql

```
SELECT  
KNOWLEDGES.* ,
USERS.USER_NAME AS INSERT_USER_NAME ,
UP_USER.USER_NAME AS UPDATE_USER_NAME 
FROM KNOWLEDGES 
LEFT OUTER JOIN USERS ON USERS.USER_ID = KNOWLEDGES.INSERT_USER 
LEFT OUTER JOIN USERS AS UP_USER ON UP_USER.USER_ID = KNOWLEDGES.UPDATE_USER 
WHERE KNOWLEDGE_ID IN (
638, 639, 636, 637, 629, 635, 452, 634, 446, 596, 632, 633, 519, 488, 39, 29, 221, 139, 47, 464, 278, 631, 613, 434, 429, 465, 305, 170, 528, 226, 467, 520, 515, 521, 244, 436, 453, 522, 457, 274, 217, 500, 494, 454, 526, 516, 444, 514, 477, 482
)
```

をh2コンソール
java -cp /usr/local/tomcat9/webapps/knowledge/WEB-INF/lib/h2-1.4.183.jar org.h2.tools.Console -webAllowOthers
で実行したところ

```
入出力例外: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 118805"
IO Exception: "java.io.IOException: org.h2.message.DbException: 入出力例外: ""java.io.IOException: java.lang.NullPointerException""
IO Exception: ""java.io.IOException: java.lang.NullPointerException"" [90028-183]"; "lob: null table: -3 id: 118805" [90031-183] 90031/90031
```

クエリを
```
SELECT  
KNOWLEDGES.TITLE ,
USERS.USER_NAME AS INSERT_USER_NAME ,
UP_USER.USER_NAME AS UPDATE_USER_NAME 
FROM KNOWLEDGES 
LEFT OUTER JOIN USERS ON USERS.USER_ID = KNOWLEDGES.INSERT_USER 
LEFT OUTER JOIN USERS AS UP_USER ON UP_USER.USER_ID = KNOWLEDGES.UPDATE_USER 
WHERE KNOWLEDGE_ID IN (
638, 639, 636, 637, 629, 635, 452, 634, 446, 596, 632, 633, 519, 488, 39, 29, 221, 139, 47, 464, 278, 631, 613, 434, 429, 465, 305, 170, 528, 226, 467, 520, 515, 521, 244, 436, 453, 522, 457, 274, 217, 500, 494, 454, 526, 516, 444, 514, 477, 482
)
```
とワイルドカード指定にしなかった場合はエラー無くコンソール上で表示されました。

**Comment by tknr** [comment]
/knowledge/open.knowledge/view/636
と個別記事にアクセスしたところ
[fail] get template info
と画面右上に表示されました。
KNOWLEDGES.CONTENT : CLOB(2147483647)
カラムがselectに入っているとnullpointerexceptionになっているようです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
アップデート前には動作できていたということでしょうか？

私の環境では、今のところ普通にバージョンアップできて動いているので、
たぶんDBに入っているデータが特定の条件の場合にエラーになるのだと思います。

上記の記事 (636の記事)のデータはどのようなものでしょうか？
差し支えなければ、ここに記載いただくか（←皆に内容が見える）、
紹介ページの最下部にあるフォームでお送りください（←私だけに通知）
https://support-project.org/knowledge_info/index

**Comment by tknr** [comment]
業務にて急務となったため
一旦1.7.0以前のイメージに戻すことで復旧を行っております。
再度1.7.0アップグレード時に発生いたしましたらご報告させて下さい。
