### ISSUE TITLE
debian8の最新のtomcat8で利用するとエラー

### ISSUE THREAD

**Issue by thisprogrammer1** [support-project/knowledge#773]
データベース操作をするアクションを起こすと次のようなエラーになる。

javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
	at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1580)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1537)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: java.lang.NullPointerException
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:216)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:293)
	... 28 more
Caused by: java.lang.NullPointerException
	at org.support.project.web.logic.HttpRequestCheckLogic.checkReferrer(HttpRequestCheckLogic.java:64)
	at org.support.project.web.logic.HttpRequestCheckLogic.checkCSRF(HttpRequestCheckLogic.java:200)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:172)
	... 34 more

**Comment by thisprogrammer1** [comment]
.knowledgeフォルダを一回削除したら正常に動くようになりました。これってどうにかなりませんか？

**Comment by koda-masaru** [comment]
@thisprogrammer1 さん
エラーのログありがとうございます。原因を見ると、ブラウザのHttpヘッダーのREFERERが無い場合のエラーのようです。（たぶん `.knowledgeフォルダを一回削除` は関係無いと思います）

```
        String referrer = request.getHeader("REFERER");
-        if (referrer.startsWith(url)) {
+        if (StringUtils.isNotEmpty(referrer) && referrer.startsWith(url)) {
             return true;
         }
```



次回のリリースで、REFERERが取れない場合でもエラーにならないように修正しようと思います。

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
