### ISSUE TITLE
LDAP使用時に内部エラーが発生してしまいログインできない

### ISSUE THREAD

**Issue by ikuko** [support-project/knowledge#785]
1.10.0pre1を手元の環境に入れてみました。
LDAPユーザーが以下のようなエラーになってしまいログインできませんでした。
内部ユーザー(admin)はログインできているので #657 の変更が影響しているのかもしれません

```
ERROR 2017-07-05 11:24:18,545 [Transaction(58)] Error(Rollback) : org.support.project.web.logic.impl.DefaultAuthenticationLogicImpl_$$_jvst990_6#_d0auth
INFO  2017-07-05 11:24:18,546 [Intercepter(213)] error. [object]class org.support.project.web.logic.impl.DefaultAuthenticationLogicImpl_$$_jvst990_6[proceed]_d0auth[param0]User1[param1]password
[throwable.getMessage()] null
ERROR 2017-07-05 11:24:18,547 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: java.lang.NullPointerException
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
    at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.knowledge.filter.ApiFilter.doFilter(ApiFilter.java:71)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
    at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.support.project.web.logic.impl.DefaultAuthenticationLogicImpl.auth(DefaultAuthenticationLogicImpl.java:223)
    at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:48)
    at org.support.project.web.filter.AuthenticationFilter.doLogin(AuthenticationFilter.java:347)
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:205)
    ... 29 more
INFO  2017-07-05 11:24:18,548 [LoggingFilter(100)] POST     http://xxxxx/knowledge/signin   200     10.184.153.31   50[ms]
```

＃いろいろ伏せるの忘れてました。。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます 🙇 
ご指摘のように、#657 による不具合のようです。
先程修正しました。
修正版を、近日中に、 v1.10.0 pre2 として公開したいと思います。

**Comment by ikuko** [comment]
手元の環境で問題ないこと確認できました。
素早い修正ありがとうございました。

**Comment by koda-masaru** [comment]
v1.10系でリリース済。クローズします。
