### ISSUE TITLE
LDAP設定 Bind DNのActiveDirectry用記述の確認

### ISSUE THREAD

**Issue by hiroG3** [support-project/knowledge#788]
お世話になっております。
ひととおり記述が見当たらないようですので、こちらへ投稿いたします。

下名の環境は、LDAP認証でActiveDirectryの情報を取得する予定でおります。
そこで、LDAP設定画面にある[Config2]タブのBind DNを
　『administrator@example.co.jp』
と記述し、接続確認してみたところ
ブラウザの種類にかかわらず、下記のExceptionが表示されます。

```
ERROR 2017-07-06 11:41:31,934 [ControlManagerFilter(206)] ERROR SEND
ERROR 2017-07-06 11:41:31,935 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
	at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:216)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:293)
	... 28 more
Caused by: org.support.project.common.exception.SystemException: 
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:136)
	at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:106)
	at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:345)
	at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:31)
	at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:184)
	... 34 more
Caused by: java.lang.reflect.InvocationTargetException
	at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:132)
	... 38 more
Caused by: org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is null
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSession(LdapNetworkConnection.java:270)
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.unBind(LdapNetworkConnection.java:1798)
	at org.support.project.web.logic.LdapLogic.check(LdapLogic.java:106)
	at org.support.project.knowledge.control.admin.LdapControl.check(LdapControl.java:190)
	... 39 more
```

仮に認証先がActiveDirectoryではないものとして、Bind DNの記述を
　『CN=administrator,DC=example,DC=co,DC=jp』
に変更し接続確認すると、Exceptionは発生しません。
（もちろん『接続できません。・・・』のメッセージは表示されます）

そこで確認ですが、
BindDNの文字列は、ActiveDirectory用の記述には
対応されていないのでしょうか？

お忙しいところ申し訳ございません。
回答いただければ幸いです。

よろしくお願いします。

**Comment by koda-masaru** [comment]
> そこで、LDAP設定画面にある[Config2]タブのBind DNを
> 　『administrator@example.co.jp』
> と記述し、接続確認してみたところ

UIにかかれている通りに、そこには、Bind用のDNを指定してください。
（ユーザのメールアドレスではありません。）

私の環境でもActiveDirectoryで認証をしていますが、普通のBind用のDNを指定し、接続することができております。
LDAP（ActiveDirectory）の設定に関しては、ご利用の企業ごとに設定が異なるかと思いますので、システム管理者にお問い合わせいただくのが良いかと思います。

**Comment by hiroG3** [comment]
koda-masaru 様

回答いただきありがとうございます。
ご連絡が遅れ申し訳ありません。

ActiveDirectoryに対して認証する場合のBind DNの記述は
メールアドレスのような形式しか受け付けないと、
誤った認識をしておりました。
大変失礼いたしました。

無事、認証できましたのでクローズといたします。
