### ISSUE TITLE
Eclipseでビルドする際にFailed to run taskが発生する。

### ISSUE THREAD

**Issue by takerushi** [support-project/knowledge#798]
`pom.xml` でエラーが発生します。
原因が分からず困っています。

該当箇所
```xml
<execution>
    <id>bower install</id>
    <goals>
        <goal>bower</goal>
    </goals>
    <configuration>
        <arguments>install</arguments>
    </configuration>
</execution>
```

エラー内容
```
Failed to run task (com.github.eirslett:frontend-maven-plugin:1.3:bower:bower install:generate-resources)

org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:42)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 32 more
```

**Comment by koda-masaru** [comment]
フロントエンドライブラリを bower というツールでインストールしているのですが、そのインストールで失敗していると思います。Mavenからbowerを呼び出しているのですが、それがなんらかのエラーになっています。

bower について
- http://qiita.com/oreo3@github/items/eb790fc091aa28af8d33

Mavenから呼び出すと原因がわかりづらいので、ご利用の環境でbowerを直接インストールし、Knowledgeのディレクトリで

```
$ bower install
```

を試してみてください。

-------

bower は 非推奨 になったので、ライブラリ管理を npm か yarnに変更しようと考えていますが、時間がとれていません。もしかすると、bowerがエラーになるようになったのかも（？）

**Comment by takerushi** [comment]
@koda-masaru 
ご回答ありがとうございます。`bower install` の結果はこのようになりました。
```
> node -v
v6.11.0
> npm -v
3.10.10
> npm install -g bower
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
C:\Users\[USER]\AppData\Roaming\npm\bower -> C:\Users\[USER]\AppData\Roamin\npm\node_modules\bower\bin\bower
C:\Users\[USER]\AppData\Roaming\npm
`-- bower@1.8.0
> bower -v
1.8.0
> cd [knowledgeのプロジェクト]
> bower install
bower teambox.free-file-icons#* ENOGIT git is not installed or not in the PATH
```

> bower は 非推奨 になった

いずれはnpmからYarnに変更する必要がありそうですね。 [https://github.com/bower/bower/issues/2467](https://github.com/bower/bower/issues/2467)

**Comment by takerushi** [comment]
`bower teambox.free-file-icons#* ENOGIT git is not installed or not in the PATH` について調べるとここにたどり着きました。
[https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path](https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path)

下記を試したところ `bower install` が通りました。

**Comment by takerushi** [comment]
間違って閉じてしまいました。  
`bower teambox.free-file-icons#* ENOGIT git is not installed or not in the PATH` について調べると[ここ](https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path) にたどり着きました。

そして、[ここ](https://git-for-windows.github.io/) からGitをインストールしたところ `bower install` が通りました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
Gitが無いといけなかったのですね。
Git無しの環境で操作したことがなかったので、知りませんでした。
参考になりました :bow:

**Comment by takerushi** [comment]
開発環境の構築手順（ビルドに何が必要か）を簡単にまとめた文書がWikiにあると嬉しいです。
とりあえず、「Gitが必要」ということで解決しましたのでこのコメントを確認次第クローズしてかまいません。
（クローズされないissueが大量にあっていずれ管理が大変になりそうなので心配です。。）

**Comment by koda-masaru** [comment]
> 開発環境の構築手順（ビルドに何が必要か）を簡単にまとめた文書がWikiにあると嬉しいです。

確かにそうですね。ただ、いろいろ整備する時間が無いのでご不便をおかけします。
まずはWebAPIの仕様書からかな、、、と思っています。

> クローズされないissueが大量にあっていずれ管理が大変になりそうなので心配です

ご配慮ありがとうございます。
まとまった時間がとれるときに、Issueのクローズ大会をしようと思っているのですが、なかなか時間がとれないで困っている感じです。

とりあえず、本Issueはクローズしようと思います。
