### ISSUE TITLE
When knowledge runs on Apache with SSL through Tomcat, it had happened error message that is "HTTP upgrade is not supported by the AJP protocol".

### ISSUE THREAD

**Issue by MatsumotoHiroko** [support-project/knowledge#827]
Thank you for your reading this topic.
I have been using knowledge on Apache with SSL through Tomcat.
When I selected "system setting" at "index rebuilding" or another some menus, it had occurred 500 error in "catalina.out".
It included a message which was "HTTP upgrade is not supported by the AJP protocol".
After error happened, I checked and set up Apache's module which name is "mod_proxy_wstunnel".

But I haven't resolved this error... 

Please anyone help me. Thank you.

**My machine environment**
```
OS: Amazon Linux(CentOS6)
Tomcat: Apache Tomcat/8.0.45
Apache: 2.4.27
Java: openjdk version "1.8.0_141"
knowledge: 1.10.0
```

**/etc/httpd/conf.modules.d/00-proxy.conf**
```
# This file configures all the proxy modules:
LoadModule proxy_module modules/mod_proxy.so
LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
LoadModule lbmethod_bytraffic_module modules/mod_lbmethod_bytraffic.so
LoadModule lbmethod_heartbeat_module modules/mod_lbmethod_heartbeat.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule proxy_connect_module modules/mod_proxy_connect.so
LoadModule proxy_express_module modules/mod_proxy_express.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule proxy_fdpass_module modules/mod_proxy_fdpass.so
LoadModule proxy_ftp_module modules/mod_proxy_ftp.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_hcheck_module modules/mod_proxy_hcheck.so
LoadModule proxy_scgi_module modules/mod_proxy_scgi.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
```

**/etc/httpd/conf.d/wstunnel.conf**
```
ProxyPass /knowledge ajp://localhost:8009/knowledge
```

**/etc/tomcat8/server.xml**
 ```
<!-- A "Connector" represents an endpoint by which requests are received
         and responses are returned. Documentation at :
         Java HTTP Connector: /docs/config/http.html (blocking & non-blocking)
         Java AJP  Connector: /docs/config/ajp.html
         APR (HTTP/AJP) Connector: /docs/apr.html
         Define a non-SSL/TLS HTTP/1.1 Connector on port 8080
    -->
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />


<!-- Define an AJP 1.3 Connector on port 8009 -->
    <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
```

**Error message**
```
INFO  2017-08-17 07:29:01,969 [LoggingFilter(100)] GET    https://example.co.jp/knowledge/admin.database/reindexing    200    IPADDRESS    17[ms]
INFO  2017-08-17 07:29:02,057 [LoggingFilter(100)] GET    https://example.co.jp/knowledge/open.account/icon/1    200    IPADDRESS    3[ms]
ERROR 2017-08-17 07:29:02,578 [ControlManagerFilter(206)] ERROR SEND
ERROR 2017-08-17 07:29:02,578 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.UnsupportedOperationException: HTTP upgrade is not supported by the AJP protocol
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
    at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.knowledge.filter.ApiFilter.doFilter(ApiFilter.java:71)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
    at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:877)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: java.lang.UnsupportedOperationException: HTTP upgrade is not supported by the AJP protocol
    at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:216)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:293)
    ... 30 more
Caused by: java.lang.UnsupportedOperationException: HTTP upgrade is not supported by the AJP protocol
    at org.apache.coyote.ajp.AbstractAjpProcessor.action(AbstractAjpProcessor.java:619)
    at org.apache.coyote.Request.action(Request.java:380)
    at org.apache.catalina.connector.Request.upgrade(Request.java:1932)
    at org.apache.catalina.connector.RequestFacade.upgrade(RequestFacade.java:1114)
    at javax.servlet.http.HttpServletRequestWrapper.upgrade(HttpServletRequestWrapper.java:376)
    at javax.servlet.http.HttpServletRequestWrapper.upgrade(HttpServletRequestWrapper.java:376)
    at org.apache.tomcat.websocket.server.UpgradeUtil.doUpgrade(UpgradeUtil.java:234)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:77)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:191)
    ... 36 more
INFO  2017-08-17 07:29:02,579 [LoggingFilter(100)] GET    https://example.co.jp/knowledge/reindexing    500    IPADDRESS    2[ms]
```

**Comment by MatsumotoHiroko** [comment]
すみません、思い当たることがあったので一旦取り下げます

**Comment by MatsumotoHiroko** [comment]
大変すみません、調査しましたがやはり解決できず…
お手すきの際にご精査願えますと幸いです 🙇‍♀️ 
knowledge内でおそらく、HTTP1.1でリクエストを投げている場所があり、そこを何かしら受けられる設定が必要だという想定ではおりますが、AJPとHTTP1.1を共存させる書き方をしてもHTTP1.1の非サポートエラー？が出てしまう状況は変わりませんでした。

**Comment by koda-masaru** [comment]
私は最近はリバースプロキシはNginxを使うことがほとんどで、Apacheを前に置いた構成は自信がないのですが、少し気になったところを記載します。

上記の設定を見たのですが、Tomcatの設定を修正したほうが良い気がします。
ご利用の環境は、以下のような感じでしょうか？

ブラウザ ------ HTTPS or HTTP -----> (80 or 443) Apache ------- AJP ------> (8009) Tomcat(launch Knowledge)
※Apacheで、HTTPのリクエストが来た場合HTTPSにリダイレクトする
　Aacheが443で受けたリクエストは、AJPでTomcatにフォワードする

上記のように動かすのであれば、Tomcatの設定のリダイレクトはいらないような気がします。

```
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
                                redirectPort がいらない（？）
```

でないと、Apacheが443で受けたリクエストを、今度は8443ポートにリダイレクトしてしまうような、、、

このへんのサイトを参考に回答を書きました。間違っていたらすみません。
https://ja.confluence.atlassian.com/adminjiraserver071/configuring-apache-reverse-proxy-using-the-ajp-protocol-802593042.html

**Comment by MatsumotoHiroko** [comment]
お忙しい中、確認いただきまして本当にありがとうございます。
@koda-masaru　様と @Monota 様のご指摘通りの指定をしてみましたが、エラーが発生する状態です。


**/etc/httpd/conf.d/wstunnel.conf**
```
ProxyPass /knowledge ws://localhost:8180/knowledge
ProxyPassReverse /knowledge ws://localhost:8180/knowledge
ProxyPass /knowledge ajp://localhost:8009/knowledge
```

**/etc/tomcat8/server.xml**
```
<Connector port="8180" protocol="HTTP/1.1"
               connectionTimeout="20000" />
<Connector port="8009" protocol="AJP/1.3" />
```

のように指定をいたしました。

大変恐れ入りますが、WebSocket 通信がどの機能に採用されているかをお教えいただくことはできますでしょうか？

http://normalse.hatenablog.jp/entry/2015/03/13/200755
の情報を見た限り、websocketの対象のURIとajpのURIが共存できない？ようでして、機能別のURIを指定する必要がありそうです。

catarina.outで把握する限り、

knowledge/data_transfer (データベースの接続先変更)
knowledge/admin.database/start_reindexing(検索用のインデックスの再作成)

この２つの機能ではwebsocketが使われているようですが、他にも使われている場所はありますでしょうか…？
大変恐れ入りますが、特定方法などありましたらご教授願えますと幸いです。
(もし、websocket利用箇所がインデックスの再作成くらいでしたら、場合によっては再作成の時はtomcatのみで起動することで逃れようとも考えております。)

**Comment by Monota** [comment]
私も WebSocket の実装はしたことありませんが、ざっとソースコードを眺めた感じだと

```
ProxyPass /knowledge/exporting ws://localhost:8180/knowledge/exporting
ProxyPass /knowledge/data_transfer ws://localhost:8180/knowledge/data_transfer
ProxyPass /knowledge/notify ws://localhost:8180/knowledge/notify
ProxyPass /knowledge/reindexing ws://localhost:8180/knowledge/reindexing
```

を先頭に書くとどうでしょうか？

```org.support.project.knowledge.websocket``` パッケージの実装を参照して書きました。

**Comment by koda-masaru** [comment]
WebSocketが問題だったのですね。勉強になりました。

@Monota さんが上で書かれているとおりのエンドポイントでWebSocketを使っています。

特に、`knowledge/notify` が良く使われている部分で、デスクトップ通知をONにしているユーザへの通知を処理するところになります。

**Comment by MatsumotoHiroko** [comment]
@Monota 様、ありがとうございます。そちらの内容をproxyのconfに記載の上でtomcat + apache再起動したところ、今度はインデックス再構築でエラーがなく成功しました。（成功後メッセージポップアップは出てきませんがログ上では終わっていますので問題なさそうです）
実装確認をありがとうございます。

@koda-masaru 様、利用箇所のご説明ありがとうございます。デスクトップ通知でwebsocektが使われているのですね。あまり知見がないため非常に勉強になりました。

本当に感謝いたします。皆様がApacheを使っていないというのをお聞きし、HTTPサーバーの選択を誤りました。なんとか解決してよかったです。ありがとうございます 🙇‍♀️
