### ISSUE TITLE
削除済みグループで絞り込むと『Internal Server Error』

### ISSUE THREAD

**Issue by hiroG3** [support-project/knowledge#861]
お世話になっております。

一通りIssuesを確認しましたが、なさそうでしたので投稿します。
ある動作を行うと『Internal Server Error』の表示になりましたので、以下に詳細を記載します。

---
事象
--
『Internal Server Error』が発生。

【ログ(app.log)一部抜粋】
INFO  2017-09-19 09:51:19,725 [Intercepter(213)] error. [object]class org.support.project.knowledge.logic.KnowledgeLogic_$$_jvst4ca_a[proceed]_d34showKnowledgeOnGroup[param0]13[param1]org.support.project.web.bean.LoginedUser@9fde5a[param2]0[param3]50
[throwable.getMessage()] null
ERROR 2017-09-19 09:51:19,725 [ControlManagerFilter(206)] ERROR SEND
ERROR 2017-09-19 09:51:19,725 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException: 
	at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:300)
	at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.knowledge.filter.ApiFilter.doFilter(ApiFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

発生手順
--
①投稿済みのナレッジで公開先に指定されているグループを削除します。
②TOP画面(ナレッジ一覧画面)に移動し、リスト上で①のグループをクリックします。

発生環境
--
バージョン：1.10.0
ブラウザ：Chrome

---

グループが削除されていても絞り込まれるのを期待しておりましたが、これは仕様でしょうか？

お忙しいところ申し訳ございません。
ご確認いただければ幸いです。
よろしくお願いいたします。

**Comment by koda-masaru** [comment]
> グループが削除されていても絞り込まれる

グループが削除されている場合は、その条件を使っての絞り込みができなくなるというのが仕様になります。

また、①の後に、ナレッジの一覧画面を開くと、削除されたグループは右側のグループ一覧には表示されないようになっています。このため、「②のリスト上で①のグループをクリック」はできなかったのですが、どのように操作したのでしょうか？
※ [テストサイト](https://test-knowledge.support-project.org/open.knowledge/list) で確認しました。

**Comment by hiroG3** [comment]
koda-masaru 様

回答いただきありがとうございます。

>また、①の後に、ナレッジの一覧画面を開くと、削除されたグループは右側のグループ一覧には表示されないようになっています。このため、「②のリスト上で①のグループをクリック」はできなかったのですが、どのように操作したのでしょうか？

わかりづらい説明で申し訳ございませんでした。
具体的な操作は以下の通りです。

【手順1】user1がグループA [所属員：user1(管理者)、user2(メンバー)] を作成。
【手順2】user2が公開先：グループAのナレッジを投稿。
【手順3】user1がグループAを削除。
【手順4】user2がナレッジ一覧画面を表示し、左側の一覧の中から【手順2】で投稿したナレッジの公開先をクリック。→<事象発生>

ナレッジ投稿時に指定した公開先のグループが、グループ管理者（自分 or 他人）によって削除されたとき、
そのグループを指定（ナレッジ一覧でグループをクリック）すると事象が発生するのでは？と推測されます。
なお、この事象は公開先が『削除されたグループ』だけではなく、『削除されたユーザ』（表記は『Remover User』）であっても同じことが起こります。

>※ テストサイト で確認しました。

改めてテストサイトでも試してみましたが、同様の事象が発生しました。

>グループが削除されている場合は、その条件を使っての絞り込みができなくなるというのが仕様になります。

仕様ということで理解しました。
ただ個人的な意見ですが、投稿者の知らない間に公開先が管理者（他人）によって削除されたのであれば、
削除されたことがわかるように表記、またはグループ名をマスク（クリック無効やグレイアウト表示）してはいかがでしょうか？

優先度はかなり低いと思いますが、ご検討いただければ幸いです。

よろしくお願いいたします。

**Comment by koda-masaru** [comment]
詳細のご連絡ありがとうございます。
グループの削除でエラーが発生するのは問題だと思いますので、修正しようと思います。
たぶん、削除済になっているグループ名が表示されてしまっているのが混乱の原因かなと思いました。
後でもう少しちゃんと検討します。

**Comment by koda-masaru** [comment]
This is fixed by v1.11.0.
I will close this.
