### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: メモリが不足しています

### ISSUE THREAD

**Issue by thisprogrammer1** [support-project/knowledge#885]
Caused by: org.h2.jdbc.JdbcSQLException: メモリが不足しています
Out of memory.; SQL statement:
COMMIT [90108-183]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convert(DbException.java:289)
        at org.h2.command.Command.executeUpdate(Command.java:260)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:345)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:159)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Capacity: 4718592
        at org.h2.mvstore.WriteBuffer.grow(WriteBuffer.java:310)
        at org.h2.mvstore.WriteBuffer.ensureCapacity(WriteBuffer.java:295)
        at org.h2.mvstore.WriteBuffer.put(WriteBuffer.java:157)

...

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(App$
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Application$
        at org.support.project.web.filter.AuthenticationFilter.doFilter(Authent$
        ... 31 more
Caused by: org.support.project.common.exception.SystemException:
        at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:$
        at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java$
        at org.support.project.web.filter.ControlManagerFilter.doInvoke(Control$
        at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.ja$
        at org.support.project.web.filter.ControlManagerFilter.doFilter(Control$
        ... 37 more
Caused by: java.lang.reflect.InvocationTargetException
        at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:$
        ... 41 more
Caused by: org.support.project.ormapping.exception.ORMappingException: データベ$
The database has been closed [90098-183] [cause] データベースはすでに閉じられて$
The database has been closed [90098-183]

のようなエラーが発生します。改善は可能でしょうか？宜しくお願い致します。

**Comment by koda-masaru** [comment]
Please  refer to [this page](https://www.ibm.com/support/knowledgecenter/ja/SSQP76_8.7.1/com.ibm.odm.distrib.troubleshooting/shared_config_tomcat_topics/trb_tomcat_more_memory.html) and increase the memory of Tomcat.

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
